# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "PCDatabaseCoreExampleApp" do
	pod 'PCDatabaseCore', :git => 'git@github.com:pilotcreative/PCDatabaseCore.git'
end

target "PCDatabaseCoreExampleAppTests" do

end

